title: "Cristhian Moreno"
description: "Estudiante de Derecho, Representante Estudiantil y Blog Político."
url: "https://cristhiandmoreno.github.io"
baseurl: ""
author: "Cristhian Moreno"
lang: es

# Configuración de estilo
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Paginación
paginate: 6
paginate_path: "/blog/page:num/"

# Colecciones (para eventos si quieres separarlos, o usaremos _data)
collections:
  guides:
    output: true

defaults:
  - scope:
      path: "" # Configuración global para posts normales
      type: "posts"
    values:
      layout: "post"
  
  # CONFIGURACIÓN ESPECÍFICA PARA EL INCONFORME
  - scope:
      path: "_posts/el-inconforme" # Debes crear esta carpeta dentro de _posts
      type: "posts"
    values:
      layout: "newspaper" # Usará el nuevo diseño que crearemos abajo
      permalink: /el-inconforme/:title/ # Forza la URL que pediste
      categories: ["El Inconforme"] # Asigna la categoría automáticamente